name: narra
description: "Narra - Ayuda a personas mayores a contar sus historias de vida"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  supabase_flutter: '>=1.10.0'
  http: ^1.0.0
  http_parser: ^4.0.2
  image_picker: '>=1.1.2'
  file_picker: '>=8.1.2'
  image: ^4.0.0
  uuid: ^4.0.0
  url_launcher: ^6.3.0
  # (Opcional) agregar plugin de grabaciÃ³n para mobile en una iteraciÃ³n futura

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
